### PR TITLE
Fix json boot log

### PR DESCRIPTION
**Pull request by niksiboxi**
A line breaker in the end of tests and submodules update.

### CODE REVIEW

**Comment by ojousima** [comment]
@niksiboxi please fix the merge conflict

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by DG12** [comment]
Do you have a document that explains the overall GitHub "merge acceptance steps":

At least for now, this new? What's it do?
```
pvs: $(SOURCES) $(EXECUTABLE) 

$(EXECUTABLE): $(OBJECTS)
# Converting
	plog-converter -a 'GA:1,2,3;OP:1,2,3;CS:1,2,3;MISRA:1,2,3' -t $(LOG_FORMAT) $(POBJECTS) -o $(PVS_LOG)
	plog-converter -a 'GA:1;OP:1;CS:1;MISRA:1' -t errorfile $(POBJECTS) -o ./pvs.error
```

**Comment by ojousima** [comment]
> Do you have a document that explains the overall GitHub "merge acceptance steps":

Not specifcally, but in general: If the feature is something that has been discussed and agreed on and CI passes, it can be merged. 

> At least for now, this new? What's it do?

It runs PVS Studio static analyzer and fails if there is some critical error. Non-critical errors get published as a HTML document.

**Pull request merged**
