### PR TITLE
m_boot_count was uint16 should be uint32 and comments

### PR DESCRIPTION
**Pull request by DG12**
Only functional change is correction of m_boot_count from uint16 to uint32 and corresponding sizeof(m_boot_count) NOT sizeof(uint32).
Fortunately the loader added fill bytes after m_boot_count otherwise read_boot_count rt_flash_load would have clobbered memory after m_boot_count.
WAS
```
 .bss.m_boot_count
                0x0000000020003840        0x2 _build/nrf52832_xxaa/app_log.c.o
 *fill*         0x0000000020003842        0x6

```
Change log message for store_block: to use %X not %d
Use TESTABLE_STATIC
MInor LOG changes
Add many comments

Checked astyle , build and executed.

### CODE REVIEW

**Comment by ojousima** [comment]
ok to test

**Comment by ojousima** [comment]
What is the purpose of 
`// // // // // // / // // // // // // // // // //` comment lines?

**Comment by ojousima** [comment]
> Only functional change is correction of m_boot_count from uint16 to uint32 and corresponding sizeof(m_boot_count) NOT sizeof(uint32).

Good catch, thanks

**Comment by ojousima** [comment]
Sonar error is caused by external origin, it can be ignored here

**Comment by DG12** [comment]
Comment lines like:
```
// // // // // // /           // // // // // // // // // //
static rd_status_t store_block (const app_log_record_t * const p_record)
```

Are for ease of picking out functions while scrolling though . notice spaces where name is

**Pull request merged**
