### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
How do you correlate the git commit value in the version with the git library??
By that I mean if the version includes the git commit of 233896d how can I view what is related in GitHub?

**Comment by ojousima** [comment]
> How do you correlate the git commit value in the version with the git library??
> By that I mean if the version includes the git commit of 233896d how can I view what is related in GitHub?

` git describe --tags 233896d` -> `v3.29.3-rc1-1-g233896d` 
Means that the closest tag is `v3.29.3-rc1` and it has one commit added after the tag

**Comment by DG12** [comment]
Sorry my experience with git is limited. Is there a way to do 
git describe --tags 233896d 
from the web page at GitHub??

**Comment by ojousima** [comment]
I don't know if GitHub has a feature to search for relevant tags for a commit.

**Pull request merged**
