### PR TITLE
Print version and mac

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
I'm really trying to help and these simple "test" updates are excruciatingly hard.

**Comment by ojousima** [comment]
> I'm really trying to help and these simple "test" updates are excruciatingly hard.

There is a rather steep learning curve in unit testing, but at the same time testing is necessary to keep the project manageable across different hardware and firmware configurations

**Comment by DG12** [comment]
Here are the (non commented lines from the Astyle.rc. (editor here keeps "fixing" spelling)
are these different from what the travis/astyle run uses ?
--max-code-length=90
--style=break
--attach-closing-while
--attach-extern-c
--pad-oper
--pad-paren-out
--align-pointer=middle
--unpad-paren
--delete-empty-lines
--add-one-line-braces
--break-blocks
--lineend=linux
--indent=spaces=4
--convert-tabs
--indent-switches
--indent-col1-comments

**Comment by ojousima** [comment]
> Here are the (non commented lines from the Astyle.rc. (editor here keeps "fixing" spelling)

Run `make astyle` at the root of project to format the project. That's also what Travis does.

**Pull request merged**
