### PR TITLE
Add comment block; describe on_error and init

### PR DESCRIPTION
**Pull request by DG12**
Add comment block, copyright notice etc.

Describe the on_error functionality of storing the fatal error information and init's logging of previous error.

### CODE REVIEW

**Comment by ojousima** [comment]
Can one of the admins verify this patch?

**Comment by DG12** [comment]
Gosh. That wasn't any fun! :-)

**Comment by ojousima** [comment]
Oh, looks like Jenkins uses my name on the automatic checks. I'll need to fix it :)

The issue is that the pull requests are built with a access to the server, for example malicious makefile can do a lot of damage. Therefore the PRs must be verified by one of Ruuvi's GitHub organization members

**Comment by ojousima** [comment]
Apparently it's enough if I push the commit under Ruuvi's account to run the checks, so no need to reopen the PR. Continuing here.

**Comment by ojousima** [comment]
Thank you for the contribution

**Pull request merged**
