### PR TITLE
Reintroduce longmem.h

### PR DESCRIPTION
**Pull request by DG12**
longmem.h got emptied  Jan 2020. and current releases have been providing a duplicate of the default settings since then.

### CODE REVIEW

**Comment by DG12** [comment]
astyle job options for diff should include 

 --suppress-common-lines 

Perhaps also
--ignore-all-space  
??

**Comment by ojousima** [comment]
Thanks, have you tested the build?

**Comment by ojousima** [comment]
ok to test

**Comment by ojousima** [comment]
@DG12 Have you tested the build, does it seem to work as expected?

**Comment by DG12** [comment]
Still checking FLASH.
image

3.31.1 does not seem to want to connect to ruuvi station IOS even the release version.

**Comment by DG12** [comment]
You should delete longmem versions from git release otherwise anyone who installs one will not get what they expect.

**Comment by DG12** [comment]
longmem should be removed from pre-releases since it is NOT what it's name states

**Comment by DG12** [comment]
Sorry for the brevity.
"3.31.1 does not seem to want to connect to ruuvi station IOS **even the release version**."

What I meant by this was that the release version 3.31.1  fails !
RTT shows 
```
"firmware":"Ruuvi FW  v3.31.1",
"compiled_on":"Nov  8 2021 18:54:11",
NFC SW: Ruuvi FW v3.31.1+debug
```

`BTKit: failed to connect to peripheral in desired interval. `
Although I don't know if the problem is with ruuvi station IOS

**Comment by ojousima** [comment]
> BTKit: failed to connect to peripheral in desired interval.

Thanks, this sounds like a GATT issue. @markoaamunkajo can you check the 3.31.1+default on iOS? Does the phone connect and read logs?

**Comment by DG12** [comment]
SW: Ruuvi FW v3.31.1+default  No good
+debug does not show any LOG message related to attempted connect

**Comment by ojousima** [comment]
Some issues in this PR:
1) AStyle step fails
2) Having slow BLE advertising makes it hard to connect, which makes it hard to read the logs. This goes against the purpose of having longer log memory in tag. 
3) The issue with iOS, but it may be something related to drivers.

@DG12 do you plan to address these? I could also go through longmem.h when I go through #313 , se we could drop this PR

**Comment by DG12** [comment]
1a) when I run astyle it reports "Unchanged" and exit code =0
1b) I cannot see what it's complaining about in the job 

2) "hard to connect" is a fact of life with Bluetooth. Just because some receivers have a problem is not a good reason to remove this feature for many other receivers that work.

4) This was not my idea. I was only to correct the fact that the application claimed that it has such a option and repository claimed to have firmware with this and in fact were really default.

I you feel this is an unnecessary option then I will remove it from comments, Makefile, _modes_ ...

**Pull request closed without merging**
