### PR TITLE
Add counter read/storage function

### LINKED ISSUE #144: Logging: Add a boot counter and match the boot count to log page

### PR DESCRIPTION
**Pull request by niksiboxi**
Resolve #144

### CODE REVIEW

**Comment by DG12** [comment]
Please add something like " user requested factory reset "  to app_ button.c and app_log.c

**Comment by DG12** [comment]
Please add watchdog timeout.
note. WDOG reset is delayed by 2/32,768 i.w 61ms, Flash write takes 338us leaving plant of time .

**Comment by ojousima** [comment]
SonarCloud check must pass, gh-pages can be worked on separately in issue #240

**Comment by ojousima** [comment]
> Please add circular list of last 8(?) watchdog timeout occurrence with ms since boot ie ri_rtc_millis();.
note. WDOG reset is delayed by 2/32,768 i.w 61ms, Flash write takes 338us leaving sufficient time .

This kind of additional debug information would provide very little benefit compared to the time to implement logging and readers for the logs

**Pull request merged**
