### PR TITLE
Lower sensor sample rate to 1/6 Hz

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
Just saying 1/6 = .1666, 1/8 =.1285

What prompted this?

**Comment by ojousima** [comment]
> What prompted this? 

Power consumption

**Comment by DG12** [comment]
Would you consider:
static adv_num_repeats = ADV_NUM_REPEATS;
static adv_tx_interval = 1285U;  // better if not 'magic'

For future configuration.

**Comment by ojousima** [comment]
> I cannot find where they are retrieved from flash ? Similar to app_log_init does for config.interval_s,.overflow,.fields...

Ah yes, now I understand what you meant. These aren't stored to flash right now.

**Pull request merged**
