### PR TITLE
WIP: GATT power/data throughput optimization

### PR DESCRIPTION
**Pull request by ojousima**
This pull request adds GATT integration testing for each supported PHY. 

The integration test starts advertising at 100 ms interval for 20 seconds with name "RuuviTest" and Nordic UART Service UUID, connect to the target with nRF Connect and register to Nordic UART Service TX Notifications. 
image

image

After registration, test will push 10 messages at a rate of 1 message per second. Then test will push 10 000 messages at maximum possible rate. 

This works well on Android device, slow messages are sent at a sparse interval and when there is a lot of data to send, connection event extension or similar mechanism is automatically used to push more data.
Näyttökuva 2020-6-19 kello 16 44 40

On iOS / Mac OSX this fails, there is no connection event extension enabled and data is pushed at a few packets per connection interval leading to poor throughput:

Näyttökuva 2020-6-19 kello 16 46 07

On Ruuvi Firmware 3.28.13 throughput is prioritized over power consumption and default connection interval is very fast, which leads to fast transfer rate but high power consumption when there is no data to transfer. Task here is to use connection length extensions, connection intervals and/or slave latency to save power when there isn't bulk of data to transmit and to transfer a bulk of data as fast as possible. Relevant initializations are [here](
https://github.com/ruuvi/ruuvi.drivers.c/blob/72d361f58b888e204bbbe99ed6b2481eea332f01/src/nrf5_sdk15_platform/communication/ruuvi_nrf5_sdk15_communication_radio.c#L82) and [here](https://github.com/ruuvi/ruuvi.drivers.c/blob/72d361f58b888e204bbbe99ed6b2481eea332f01/src/nrf5_sdk15_platform/communication/ruuvi_nrf5_sdk15_communication_ble_gatt.c#L633).

Another issue which may come up at 2 MBit/s modulation is iOS disconnecting when faster PHY is requested [here](https://github.com/ruuvi/ruuvi.drivers.c/blob/9d0c747d54b4a6d6b3bbb46392907eed82207cef/src/nrf5_sdk15_platform/communication/ruuvi_nrf5_sdk15_communication_ble_gatt.c#L298). 
Preferred fix would be to query capabilities of remote device and try to switch over to 2 MBit / s only if remote device can support the connection, alternatively device can pass `BLE_GAP_PHY_2MBPS | BLE_GAP_PHY_1MBPS` [here](https://github.com/ruuvi/ruuvi.drivers.c/blob/72d361f58b888e204bbbe99ed6b2481eea332f01/src/nrf5_sdk15_platform/communication/ruuvi_nrf5_sdk15_communication_ble_gatt.c#L612) and let remote initiate PHY change.

The power profiles were taken on RuuviTag B with LIS2DH12 and BME280 installed, debug log was taken on RuuviTag B with LIS2DH12, SHTC3 and BME280 installed and a wire connecting pins 31, 13 on devkit.

```
{
"firmware":"Ruuvi FW-debug",
"board":"RUUVITAG_B",
"ruuvi.boards.c":"0.7.0",
"ruuvi.drivers.c":"0.2.3",
"flash":{
"init":"pass",
"uninit":"pass",
"store":"pass",
"load":"pass",
"free":"pass",
"gc":"pass"
},
"power":{
"dcdc_internal":"pass"
},
"timer":{
"init":"pass",
"create":"pass",
"single_shot":"pass",
"repeat":"pass"
},
"scheduler":{
"init":"pass",
"execute":"pass",
"put":"pass"
},
"sensors": {
"SHTCX": {
"init":"pass",
"modes":"pass",
"configuration":"pass",
"interrupts":"skipped"
},
"NOTINIT": {
"init":"fail",
"modes":ruuvi_driver_sensor_test.c:402 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:418 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:441 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:469 WARNING: INTERNAL
"fail",
"configuration":"fail",
"interrupts":"skipped"
},
"LIS2DH12": {
"init":"pass",
"modes":"pass",
"configuration":"pass",
"interrupts":"pass"
}
},
"radio":{
"init":"pass,"
"address_set_get":"pass"
},
"ble_adv_1_mbit":{
"init":"pass",
"interval":"pass",
"extended":"pass",
"power":"pass",
"scan":"pass"
},
"ble_adv_2_mbit":{
"init":"pass",
"interval":"pass",
"extended":"pass",
"power":"pass",
"scan":"pass"
},
"ble_gatt_1_mbit":{
"init":"pass",
"tx":"pass,"
"throughput":"15218.384 bps"
},
"ble_gatt_2_mbit":{
"init":"pass",
"tx":"pass,"
"throughput":"11661.128 bps"
},
"uart":{
"init":"pass",
"tx_rx":"pass"
"rx_corrupt":"pass"
"rx_short":"pass"
},
"gpio":{
"init":"pass",
"configure":"pass",
"toggle":"pass"
},
"gpio_interrupt":{
"init":"pass",
"enable":"pass"
},
"gpio_pwm":{
"init":"pass",
"start":"pass"
},
"nfc":{
"init":"pass",
"tx_rx":"pass"
},
}<error> app: No bootloader was found

```

### CODE REVIEW

**Comment by ojousima** [comment]
@rinat-enikeev can you test this with iOS Phone and nRF Connect? Hex is attached, you need a devkit to flash it to RuuviTag. Zipped to let GH upload the file.

[gatt_test.hex.zip](https://github.com/ruuvi/ruuvi.firmware.c/files/4852088/gatt_test.hex.zip)

**Comment by rinat-enikeev** [comment]
iOS log: 

`"ble_gatt_2_mbit":{
"init":"pass",
"tx":{
"firmware":"Ruuvi FW-debug",
"board":"RUUVITAG_B",
"ruuvi.boards.c":"0.7.0",
"ruuvi.drivers.c":"0.2.3",
"flash":{
"init":"pass",
"uninit":"pass",
"store":"pass",
"load":"pass",
"free":"pass",
"gc":"pass"
},
"power":{
"dcdc_internal":"pass"
},
"timer":{
"init":"pass",
"create":"pass",
"single_shot":"pass",
"repeat":"pass"
},
"scheduler":{
"init":"pass",
"execute":"pass",
"put":"pass"
},
"sensors": {
"NOTINIT": {
"init":"skip",
},
"NOTINIT": {
"init":"fail",
"modes":ruuvi_driver_sensor_test.c:402 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:418 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:441 WARNING: INTERNAL
ruuvi_driver_sensor_test.c:469 WARNING: INTERNAL
"fail",
"configuration":"fail",
"interrupts":"skipped"
},
"LIS2DH12": {
"init":"pass",
"modes":"pass",
"configuration":"pass",
"interrupts":"pass"
}
},
"radio":{
"init":"pass,"
"address_set_get":"pass"
},
"ble_adv_1_mbit":{
"init":"pass",
"interval":"pass",
"extended":"pass",
"power":"pass",
"scan":"pass"
},
"ble_adv_2_mbit":{
"init":"pass",
"interval":"pass",
"extended":"pass",
"power":"pass",
"scan":"pass"
},
"ble_gatt_1_mbit":{
"init":"pass",
"tx":Changing MTU size is not supported
"pass,"
"throughput":"6989.341 bps"
},
"ble_gatt_2_mbit":{
"init":"pass",
"tx":`

**Comment by ojousima** [comment]
ref #55 

@rinat-enikeev What is your device model?

**Comment by rinat-enikeev** [comment]
> ref #55 
> 
> 
> 
> @rinat-enikeev What is your device model? 

iPhone XS Max

**Comment by ojousima** [comment]
This cannot be reproduced reliably, unless using MacBook Pro and Web Bluetooth. Closing for now.

**Pull request closed without merging**
