### PR TITLE
Add tmp117

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
Might I suggest that you use x7FFF as a variable instead of 32767 and xFFFF instead of 65535
since these are actually not really decimal values.

**Comment by ojousima** [comment]
> Might I suggest that you use x7FFF as a variable instead of 32767 and xFFFF instead of 65535
since these are actually not really decimal values.

Done, thanks

> As the Texas Instruments data sheet show binary for TEMP_CC consider matching that as in
TMP117_VALUE_CC_4000_MS (0b101 << TMP117_POS_CC) instead of
TMP117_VALUE_CC_4000_MS (0x05 << TMP117_POS_CC)

I guess it's matter of preference, I don't know why but I dislike 0b notation. I guess I had a compiler which did not recognize the format or something like that in some project. 

 > In tmp117_oversampling_set
Perhaps using the reg_val as an index into a table would be clearer/easier than the case statements?

It would reduce the number of rows for sure, but at the same time it would force the reader to look up the table to check what is happening. I think the compiler might convert the switch-case into a table anyway in some cases, so I'll leave that decision to the optimizer.

**Comment by DG12** [comment]
I am always in favor of letting the compiler optimize and letting the programmer to code with "readability" and especially with next weeks, next months understanding in mind.

**Comment by DG12** [comment]
Perhaps accepting "**advisory**" specifications of MIRSA-c 2012 like
_R.15.5 A function should have a single point of exit at the end_
Should be accepted.

**Comment by ojousima** [comment]
> Perhaps accepting "advisory" specifications of MIRSA-c 2012 like
R.15.5 A function should have a single point of exit at the end
Should be accepted.

If there is a compelling reason to have multiple returns, yes. I usually refactor functions to have only one return anyway.

**Pull request merged**
