### PR TITLE
Remove unused function/variable

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Review by DG12 — COMMENTED** [review]
Is PVS Studio no longer to be used?

**Comment by ojousima** [comment]
> Is PVS Studio no longer to be used?

Yes, PVS Studio changed their licensing for open source and we do not match their terms anymore.

**Review by DG12 — COMMENTED** [review]
I liked boot_count, I thought it was informative especially useful when tag was crashing in a loop.

Why didn't you like it?

**Comment by ojousima** [comment]
> Why didn't you like it?

There is no practical way for users to read it out without devkit, and it's hard even with devkit. Since it's not used in production it is bit unnecessary, and the way nRF filesystem works clutters up the flash page. Data is not replaced, it's written as "not valid" and new element is added

**Pull request merged**
