### PR TITLE
Fix #175

### LINKED ISSUE #175: 3.29.1: Logs are erased on read timeout
If log read takes over 120 seconds, watchdog resets the tag which leads to RTC loss, which leads to losing logs

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Comment by DG12** [comment]
Will this cause log to be lost if user starts sync and then moves out of range or syncing device runs out of battery?

**Comment by ojousima** [comment]
> Will this cause log to be lost if user starts sync and then moves out of range or syncing device runs out of battery? 

yes. Logs will be lost if battery runs out because timestamps are lost, but of course failure to sync should not end up erasing the logs

**Comment by DG12** [comment]
By "syncing device runs out of battery?" I meant the mobile phone.

**Comment by ojousima** [comment]
> By "syncing device runs out of battery?" I meant the mobile phone. 

In that case the 3.29.1 would erase logs too, but this PR should also fix that case.

**Pull request merged**
