### PR TITLE
Reduce debug fstorage

### PR DESCRIPTION
**Pull request by ojousima**

### CODE REVIEW

**Review by DG12 — COMMENTED** [review]
Does this simply UN-name 4 bytes?
Can you please explain this?

Does this also effect 
https://github.com/DG12/ruuvi.firmware.c/blob/master/src/targets/ruuvitag_b/armgcc/ruuvitag_b.ld

**Review by DG12 — COMMENTED** [review]
What prompted this?

Should this be reflected in 
https://github.com/DG12/ruuvi.firmware.c/blob/master/src/Makefile_dev
https://github.com/DG12/ruuvi.firmware.c/blob/master/src/Makefile

**Comment by ojousima** [comment]
> Does this simply UN-name 4 bytes?
Can you please explain this?

https://devzone.nordicsemi.com/f/nordic-q-a/47651/uicr_mbr_params_page-and-uicr_bootloader_start_address-overwrite-the-beginning-of-the-softdevice has a good explanation. Never versions of SES refuse to compile a firmware with overlapping sections. 

> What prompted this?

> Should this be reflected in
https://github.com/DG12/ruuvi.firmware.c/blob/master/src/Makefile_dev
https://github.com/DG12/ruuvi.firmware.c/blob/master/src/Makefile

SES does not compile debug binary without size optimization anymore. Current armgcc makefile still manages to fit FW in flash. If it compiles, no changes needed. If it's out of space, turn on size optimization

**Comment by DG12** [comment]
Have you considered
#define APP_SENSOR_TMP117_ENABLED 0 //  BIG one
and / or
#define APP_SENSOR_DPS310_ENABLED 0
?

**Comment by ojousima** [comment]
Those sensors are in use in some boards, they can't be disabled

**Pull request merged**
